/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { OrderDetailService } from "../orderDetail.service";
import { OrderDetailCreateInput } from "./OrderDetailCreateInput";
import { OrderDetail } from "./OrderDetail";
import { OrderDetailFindManyArgs } from "./OrderDetailFindManyArgs";
import { OrderDetailWhereUniqueInput } from "./OrderDetailWhereUniqueInput";
import { OrderDetailUpdateInput } from "./OrderDetailUpdateInput";
import { ProductFindManyArgs } from "../../product/base/ProductFindManyArgs";
import { Product } from "../../product/base/Product";
import { ProductWhereUniqueInput } from "../../product/base/ProductWhereUniqueInput";

export class OrderDetailControllerBase {
  constructor(protected readonly service: OrderDetailService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: OrderDetail })
  async createOrderDetail(
    @common.Body() data: OrderDetailCreateInput
  ): Promise<OrderDetail> {
    return await this.service.createOrderDetail({
      data: {
        ...data,

        order: data.order
          ? {
              connect: data.order,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        order: {
          select: {
            id: true,
          },
        },

        quantity: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [OrderDetail] })
  @ApiNestedQuery(OrderDetailFindManyArgs)
  async orderDetails(@common.Req() request: Request): Promise<OrderDetail[]> {
    const args = plainToClass(OrderDetailFindManyArgs, request.query);
    return this.service.orderDetails({
      ...args,
      select: {
        createdAt: true,
        id: true,

        order: {
          select: {
            id: true,
          },
        },

        quantity: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: OrderDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async orderDetail(
    @common.Param() params: OrderDetailWhereUniqueInput
  ): Promise<OrderDetail | null> {
    const result = await this.service.orderDetail({
      where: params,
      select: {
        createdAt: true,
        id: true,

        order: {
          select: {
            id: true,
          },
        },

        quantity: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: OrderDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOrderDetail(
    @common.Param() params: OrderDetailWhereUniqueInput,
    @common.Body() data: OrderDetailUpdateInput
  ): Promise<OrderDetail | null> {
    try {
      return await this.service.updateOrderDetail({
        where: params,
        data: {
          ...data,

          order: data.order
            ? {
                connect: data.order,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          order: {
            select: {
              id: true,
            },
          },

          quantity: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: OrderDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOrderDetail(
    @common.Param() params: OrderDetailWhereUniqueInput
  ): Promise<OrderDetail | null> {
    try {
      return await this.service.deleteOrderDetail({
        where: params,
        select: {
          createdAt: true,
          id: true,

          order: {
            select: {
              id: true,
            },
          },

          quantity: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/products")
  @ApiNestedQuery(ProductFindManyArgs)
  async findProducts(
    @common.Req() request: Request,
    @common.Param() params: OrderDetailWhereUniqueInput
  ): Promise<Product[]> {
    const query = plainToClass(ProductFindManyArgs, request.query);
    const results = await this.service.findProducts(params.id, {
      ...query,
      select: {
        category: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        detail: true,
        discountPrecent: true,
        id: true,
        images: true,
        name: true,

        orderDetail: {
          select: {
            id: true,
          },
        },

        price: true,
        stock: true,

        tag: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/products")
  async connectProducts(
    @common.Param() params: OrderDetailWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      products: {
        connect: body,
      },
    };
    await this.service.updateOrderDetail({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/products")
  async updateProducts(
    @common.Param() params: OrderDetailWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      products: {
        set: body,
      },
    };
    await this.service.updateOrderDetail({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/products")
  async disconnectProducts(
    @common.Param() params: OrderDetailWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      products: {
        disconnect: body,
      },
    };
    await this.service.updateOrderDetail({
      where: params,
      data,
      select: { id: true },
    });
  }
}
